# Guest image list for TGOS images (v0.0.6)

[[images]]
name = "initramfs-aarch64-busybox.cpio.gz"
version = "0.0.6"
description = "BusyBox initramfs for aarch64"
sha256 = "41e78d8dec709ee157647c609743695190791c2ae898815bb07fc905cfdf2152"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/initramfs-aarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-04-27T03:07:47Z"

[[images]]
name = "initramfs-loongarch64-busybox.cpio.gz"
version = "0.0.6"
description = "BusyBox initramfs for loongarch64"
sha256 = "a94a9e658e479745e13b6dcd328f255b46db12c2d408199f771250687c3cab98"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/initramfs-loongarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-06-08T07:54:42Z"

[[images]]
name = "initramfs-riscv64-busybox.cpio.gz"
version = "0.0.6"
description = "BusyBox initramfs for riscv64"
sha256 = "c94ca44a175ba043ef3a5f93857849234c5d8726c4389dacdb5f3158009d3ece"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/initramfs-riscv64-busybox.cpio.gz.tar.xz"
released_at = "2026-04-27T03:07:55Z"

[[images]]
name = "initramfs-x86_64-busybox.cpio.gz"
version = "0.0.6"
description = "BusyBox initramfs for x86_64"
sha256 = "ab6de06f858dc2d8114dc82ed7d011c2639101c18741d051b7908bda695614dd"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/initramfs-x86_64-busybox.cpio.gz.tar.xz"
released_at = "2026-04-27T03:08:09Z"

[[images]]
name = "qemu-aarch64"
version = "0.0.6"
description = "Guest image bundle for QEMU aarch64 virtualization"
sha256 = "7061bcc23d354a85459b7a42626a169b091785176a2ba6836a5589d81ccd8aba"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/qemu-aarch64.tar.xz"
released_at = "2026-06-05T05:51:19Z"

[[images]]
name = "qemu-loongarch64"
version = "0.0.6"
description = "Guest image bundle for QEMU LoongArch64 virtualization"
sha256 = "b77e385a46c3a5084346e8e4281ce3753cdf82047ed71a104000b99f8ef0e4e2"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/qemu-loongarch64.tar.xz"
released_at = "2026-06-08T07:54:42Z"

[[images]]
name = "qemu-riscv64"
version = "0.0.6"
description = "Guest image bundle for QEMU riscv64 virtualization"
sha256 = "8747d5a1b3be289999facf3044bb4127908f82f1b02136c1f943e2b60babb946"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/qemu-riscv64.tar.xz"
released_at = "2026-04-27T03:21:43Z"

[[images]]
name = "qemu-x86_64"
version = "0.0.8"
description = "Guest image bundle for QEMU x86_64 virtualization"
sha256 = "64434d91166bf70ebfab42481d935c68640301fd031d0836d2bdec3f82bb2e20"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/qemu-x86_64.tar.xz"
released_at = "2026-07-03T01:24:16Z"

[[images]]
name = "rootfs-aarch64-alpine.img"
version = "0.0.6"
description = "Alpine rootfs image for aarch64"
sha256 = "50d85eb85941ddf6965a0ddfcdaa3a6ccc3cb64ff268022e58b599a06b31e469"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-aarch64-alpine.img.tar.xz"
released_at = "2026-04-27T03:10:10Z"

[[images]]
name = "rootfs-aarch64-busybox.img"
version = "0.0.6"
description = "BusyBox rootfs image for aarch64"
sha256 = "d54278f65c60666f19df58241abd257514b0ad85ca54b28ac8305144972fa082"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-aarch64-busybox.img.tar.xz"
released_at = "2026-04-27T03:10:30Z"

[[images]]
name = "rootfs-aarch64-debian.img"
version = "0.0.6"
description = "Debian rootfs image for aarch64"
sha256 = "b14e0a779a1b111fde781b694436459c565e5dc03d58940dfc6f549034630820"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-aarch64-debian.img.tar.xz"
released_at = "2026-04-27T03:12:05Z"

[[images]]
name = "rootfs-loongarch64-alpine.img"
version = "0.0.6"
description = "Alpine rootfs image for loongarch64"
sha256 = "6d9e61fff8495fedc379f9304339872c0f8bb2e5f4de83642d0e7c74fe9594d9"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-loongarch64-alpine.img.tar.xz"
released_at = "2026-04-30T06:00:14Z"

[[images]]
name = "rootfs-loongarch64-busybox.img"
version = "0.0.6"
description = "BusyBox rootfs image for loongarch64"
sha256 = "62cebc7973f9d31c63056a6ed2a6417ae66787aed52df46a669377317fcbedb0"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-loongarch64-busybox.img.tar.xz"
released_at = "2026-06-08T07:54:42Z"

[[images]]
name = "rootfs-riscv64-alpine.img"
version = "0.0.6"
description = "Alpine rootfs image for riscv64"
sha256 = "32741d425ffb817aa3a63d639af6accd2a560b2c13c36516c3e1fd0fa77c60e8"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-riscv64-alpine.img.tar.xz"
released_at = "2026-04-27T03:13:58Z"

[[images]]
name = "rootfs-riscv64-busybox.img"
version = "0.0.6"
description = "BusyBox rootfs image for riscv64"
sha256 = "3b98b8f6e5216c839ebdfc3a8937fd1a4aa22ffcd06ee6ada9f69192e0bed6a5"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-riscv64-busybox.img.tar.xz"
released_at = "2026-04-27T03:14:15Z"

[[images]]
name = "rootfs-riscv64-debian.img"
version = "0.0.6"
description = "Debian rootfs image for riscv64"
sha256 = "feec7a2947e9754e356e4f288f19c8fa8f30e1c9a61f4eaf07cdc61b93165e53"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-riscv64-debian.img.tar.xz"
released_at = "2026-04-27T03:16:54Z"

[[images]]
name = "rootfs-x86_64-alpine.img"
version = "0.0.6"
description = "Alpine rootfs image for x86_64"
sha256 = "b5802048428c2421db54f54b5419bc0598f75d96249e61fa1bc33dbdd623ed59"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-x86_64-alpine.img.tar.xz"
released_at = "2026-04-27T03:18:44Z"

[[images]]
name = "rootfs-x86_64-busybox.img"
version = "0.0.6"
description = "BusyBox rootfs image for x86_64"
sha256 = "c29c6f3474f228e8dbf68b6be938a298cf6c031b4650333ff87638b99e6aee4b"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-x86_64-busybox.img.tar.xz"
released_at = "2026-04-27T03:18:53Z"

[[images]]
name = "rootfs-x86_64-debian.img"
version = "0.0.6"
description = "Debian rootfs image for x86_64"
sha256 = "116cf5129358e9908539407c88295970fd226bb060f7e84d805f93297f7b091b"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.6/rootfs-x86_64-debian.img.tar.xz"
released_at = "2026-04-27T03:20:51Z"
