# Guest image list for TGOS images (v0.0.8)

[[images]]
name = "initramfs-aarch64-busybox.cpio.gz"
version = "0.0.8"
description = "BusyBox initramfs for aarch64"
sha256 = "e2daee0e217350c00bfc463dfa035d8a07056da14ebc2ed957810aeafc8751e3"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/initramfs-aarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-07-03T01:04:49Z"

[[images]]
name = "initramfs-loongarch64-busybox.cpio.gz"
version = "0.0.8"
description = "BusyBox initramfs for loongarch64"
sha256 = "27bf18e492b44cf86e40e8c96599aa31fe57704bd32b25a3b0e36450ef8f2f64"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/initramfs-loongarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-07-03T01:05:11Z"

[[images]]
name = "initramfs-riscv64-busybox.cpio.gz"
version = "0.0.8"
description = "BusyBox initramfs for riscv64"
sha256 = "d2279791cd0a168bd1f9575543ebcf607e7de9bd931c341360d28ac1f82fe326"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/initramfs-riscv64-busybox.cpio.gz.tar.xz"
released_at = "2026-07-03T01:05:14Z"

[[images]]
name = "initramfs-x86_64-busybox.cpio.gz"
version = "0.0.8"
description = "BusyBox initramfs for x86_64"
sha256 = "5990660753edd985f2028e53d34cc141b1fd25ceb43bd0eda8de825d8695019f"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/initramfs-x86_64-busybox.cpio.gz.tar.xz"
released_at = "2026-07-03T01:05:19Z"

[[images]]
name = "qemu-aarch64"
version = "0.0.8"
description = "Guest image bundle for QEMU aarch64 virtualization"
sha256 = "f4c9ea68474e0b39e380f1929c58fb23e86ddbd9bb114a0f7a759719ba0e771f"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/qemu-aarch64.tar.xz"
released_at = "2026-07-03T01:23:09Z"

[[images]]
name = "qemu-loongarch64"
version = "0.0.8"
description = "Guest image bundle for QEMU LoongArch64 virtualization"
sha256 = "ecea7d94cd54a5d91378cd6fdca92e424149faa0c25a2695bbe5951454c95396"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/qemu-loongarch64.tar.xz"
released_at = "2026-07-03T01:23:55Z"

[[images]]
name = "qemu-riscv64"
version = "0.0.8"
description = "Guest image bundle for QEMU riscv64 virtualization"
sha256 = "2a113cf7215797da910122880c7a72527d6471a9a00562574f2a44ba718d681f"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/qemu-riscv64.tar.xz"
released_at = "2026-07-03T01:24:06Z"

[[images]]
name = "qemu-x86_64"
version = "0.0.8"
description = "Guest image bundle for QEMU x86_64 virtualization"
sha256 = "ea5e7e5a4520e1cbcfb43cb729218cc9421dc883bf5cf72fd5452c4ccda6809b"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/qemu-x86_64.tar.xz"
released_at = "2026-07-03T01:24:16Z"

[[images]]
name = "rootfs-aarch64-alpine.img"
version = "0.0.8"
description = "Alpine rootfs image for aarch64"
sha256 = "d97245a69c60f7a0b6f9d510259f79d873e3fe6277264c936c0b26418d1c3f19"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-aarch64-alpine.img.tar.xz"
released_at = "2026-07-03T01:07:19Z"

[[images]]
name = "rootfs-aarch64-busybox.img"
version = "0.0.8"
description = "BusyBox rootfs image for aarch64"
sha256 = "6870c6c4ed81b7d1642475c8a866f77a14a01f3995e0a5e788f52b95d36dc843"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-aarch64-busybox.img.tar.xz"
released_at = "2026-07-03T01:07:37Z"

[[images]]
name = "rootfs-aarch64-debian.img"
version = "0.0.8"
description = "Debian rootfs image for aarch64"
sha256 = "df1965d6d0f4bdda6e7ee22fef4ed20aefda11f4ae012a7ce0a1ada62c129ce5"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-aarch64-debian.img.tar.xz"
released_at = "2026-07-03T01:10:03Z"

[[images]]
name = "rootfs-loongarch64-alpine.img"
version = "0.0.8"
description = "Alpine rootfs image for loongarch64"
sha256 = "25443ad55c76d810532f24f6868ce66923f58b423b3d6253cec03e8c4cc4c882"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-loongarch64-alpine.img.tar.xz"
released_at = "2026-07-03T01:12:05Z"

[[images]]
name = "rootfs-loongarch64-busybox.img"
version = "0.0.8"
description = "BusyBox rootfs image for loongarch64"
sha256 = "dd165f1f8b59acc8cc805d0c65939144f275cdbcd2eff09f80d4b997a05e2b57"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-loongarch64-busybox.img.tar.xz"
released_at = "2026-07-03T01:12:25Z"

[[images]]
name = "rootfs-riscv64-alpine.img"
version = "0.0.8"
description = "Alpine rootfs image for riscv64"
sha256 = "2b8c812d0dbac6338298793b488b3580fa81ce4e10384eac033cecc90d882b33"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-riscv64-alpine.img.tar.xz"
released_at = "2026-07-03T01:15:50Z"

[[images]]
name = "rootfs-riscv64-busybox.img"
version = "0.0.8"
description = "BusyBox rootfs image for riscv64"
sha256 = "0e35558748b3de20b4cdf440d630d634a959706faf132edbed281a7c8f4f1cdd"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-riscv64-busybox.img.tar.xz"
released_at = "2026-07-03T01:16:10Z"

[[images]]
name = "rootfs-riscv64-debian.img"
version = "0.0.8"
description = "Debian rootfs image for riscv64"
sha256 = "21510bff9b2a0f843f7dfe4998ba7bce049deddd0a3ca0c3dfa0e7d296753281"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-riscv64-debian.img.tar.xz"
released_at = "2026-07-03T01:18:31Z"

[[images]]
name = "rootfs-x86_64-alpine.img"
version = "0.0.8"
description = "Alpine rootfs image for x86_64"
sha256 = "d3aef26653deb9db4187e45171aa3e7f482160e58741e4fe9156e3b547f24528"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-x86_64-alpine.img.tar.xz"
released_at = "2026-07-03T01:20:40Z"

[[images]]
name = "rootfs-x86_64-busybox.img"
version = "0.0.8"
description = "BusyBox rootfs image for x86_64"
sha256 = "862ad70533a5e7d2c0f8a52f71736fe35074ed6d8160eeaaa64f8d57e14f0a35"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-x86_64-busybox.img.tar.xz"
released_at = "2026-07-03T01:20:47Z"

[[images]]
name = "rootfs-x86_64-debian.img"
version = "0.0.8"
description = "Debian rootfs image for x86_64"
sha256 = "6cf7302c021be61eaf60835d6a8272309e7cbaeb220cde96a188e1137ee7e862"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.8/rootfs-x86_64-debian.img.tar.xz"
released_at = "2026-07-03T01:22:33Z"
