# Guest image list for TGOS images (v0.0.11)

[[images]]
name = "initramfs-aarch64-busybox.cpio.gz"
version = "0.0.11"
description = "BusyBox initramfs for aarch64"
sha256 = "d875792d847156317b9b8fb619fc6f44af8c629538c9e2617b8d7641a0f91809"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/initramfs-aarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-08-11T02:33:25Z"

[[images]]
name = "initramfs-loongarch64-busybox.cpio.gz"
version = "0.0.11"
description = "BusyBox initramfs for loongarch64"
sha256 = "aa40d5a18a630a9e0baeb913aed7c67c9d26e6d264680f6c636462e904d0562b"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/initramfs-loongarch64-busybox.cpio.gz.tar.xz"
released_at = "2026-08-11T02:33:48Z"

[[images]]
name = "initramfs-riscv64-busybox.cpio.gz"
version = "0.0.11"
description = "BusyBox initramfs for riscv64"
sha256 = "213e4c926580421290ebec99bddea3540171c3b345d25990d461d8bf7cea4789"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/initramfs-riscv64-busybox.cpio.gz.tar.xz"
released_at = "2026-08-11T02:33:51Z"

[[images]]
name = "initramfs-x86_64-busybox.cpio.gz"
version = "0.0.11"
description = "BusyBox initramfs for x86_64"
sha256 = "bc376ec57b815e60b97bab2074651e34f647de93b0d6acddee31ecf84fc2e458"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/initramfs-x86_64-busybox.cpio.gz.tar.xz"
released_at = "2026-08-11T02:33:56Z"

[[images]]
name = "orangepi-5-plus-starry"
version = "0.0.11"
description = "StarryOS for Orange Pi development board"
sha256 = "78974bbded1bd73da6030a876be8e246d88062b709df9cd31496af01298198b9"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/orangepi-5-plus-starry.tar.xz"
released_at = "2026-08-11T02:50:33Z"

[[images]]
name = "phytiumpi"
version = "0.0.11"
description = "Guest image bundle for Phytium Pi development board"
sha256 = "2f588c4a6b6172a07145917f98dd75a2a6dfd2ff3b273bb765e41d38641b9d82"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/phytiumpi.tar.xz"
released_at = "2026-08-11T02:50:38Z"

[[images]]
name = "qemu-aarch64"
version = "0.0.11"
description = "Guest image bundle for QEMU aarch64 virtualization"
sha256 = "4078a53cbcafaa0576d65f3149fd94e3e28f3fcff3ed57a15233e4b1de9a5465"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/qemu-aarch64.tar.xz"
released_at = "2026-08-11T02:51:15Z"

[[images]]
name = "qemu-loongarch64"
version = "0.0.11"
description = "Guest image bundle for QEMU LoongArch64 virtualization"
sha256 = "da53fde968aec9f3a8933d5a88bb2260c6ff20ad2e22d954d360cbe86b520c92"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/qemu-loongarch64.tar.xz"
released_at = "2026-08-11T02:52:08Z"

[[images]]
name = "qemu-riscv64"
version = "0.0.11"
description = "Guest image bundle for QEMU riscv64 virtualization"
sha256 = "19bb9bb1e44031c6ae3d7a585809d70c36e6e6f8f714e8fb1287e390e94fb11f"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/qemu-riscv64.tar.xz"
released_at = "2026-08-11T02:52:19Z"

[[images]]
name = "qemu-x86_64"
version = "0.0.11"
description = "Guest image bundle for QEMU x86_64 virtualization"
sha256 = "42b734272f0041adb8ff6e62f2b77d06279f6953fef2d9abf6d6877252f70aea"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/qemu-x86_64.tar.xz"
released_at = "2026-08-11T02:52:25Z"

[[images]]
name = "rootfs-aarch64-alpine.img"
version = "0.0.11"
description = "Alpine rootfs image for aarch64"
sha256 = "a54b2172097d2e68e8e1e0bf3ba817f3fbfa10a2d05bcdf7b2d55771bbc79d62"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-aarch64-alpine.img.tar.xz"
released_at = "2026-08-11T02:35:45Z"

[[images]]
name = "rootfs-aarch64-busybox.img"
version = "0.0.11"
description = "BusyBox rootfs image for aarch64"
sha256 = "3ed4d732e602adf02ec66c466e6df8fed9ec9b927b5fa36934659db9a06b9cf3"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-aarch64-busybox.img.tar.xz"
released_at = "2026-08-11T02:36:01Z"

[[images]]
name = "rootfs-aarch64-debian.img"
version = "0.0.11"
description = "Debian rootfs image for aarch64"
sha256 = "5e94c7d4fbdbfb9e25cbf820c58c2227d1741f537d121b32d696b8805774e317"
arch = "aarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-aarch64-debian.img.tar.xz"
released_at = "2026-08-11T02:37:40Z"

[[images]]
name = "rootfs-loongarch64-alpine.img"
version = "0.0.11"
description = "Alpine rootfs image for loongarch64"
sha256 = "4e691210dec612e3388ee525979352e7a60dad2d56f96b004c9b77e1c8a7cdf3"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-loongarch64-alpine.img.tar.xz"
released_at = "2026-08-11T02:39:39Z"

[[images]]
name = "rootfs-loongarch64-busybox.img"
version = "0.0.11"
description = "BusyBox rootfs image for loongarch64"
sha256 = "22b67921ff222f11a710b39f51255a61c68767d090f32e275cc680ee809a4aec"
arch = "loongarch64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-loongarch64-busybox.img.tar.xz"
released_at = "2026-08-11T02:40:31Z"

[[images]]
name = "rootfs-riscv64-alpine.img"
version = "0.0.11"
description = "Alpine rootfs image for riscv64"
sha256 = "33d399dbe09d5db82b7cb5fb84e1dbeb83b5cae25f955a3e38e8d39eaac3b1df"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-riscv64-alpine.img.tar.xz"
released_at = "2026-08-11T02:42:34Z"

[[images]]
name = "rootfs-riscv64-busybox.img"
version = "0.0.11"
description = "BusyBox rootfs image for riscv64"
sha256 = "d1d54557a0399b49fdb2ddb620cca132f9e69fb6475a7d62c67e4fcceab2cebd"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-riscv64-busybox.img.tar.xz"
released_at = "2026-08-11T02:42:53Z"

[[images]]
name = "rootfs-riscv64-debian.img"
version = "0.0.11"
description = "Debian rootfs image for riscv64"
sha256 = "4072568c356f485fdef929e9f16ca1938ccc9d8c539273d62d34e6920dc868e4"
arch = "riscv64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-riscv64-debian.img.tar.xz"
released_at = "2026-08-11T02:44:47Z"

[[images]]
name = "rootfs-x86_64-alpine.img"
version = "0.0.11"
description = "Alpine rootfs image for x86_64"
sha256 = "d8cda4ef7803eb831e0be18937188214434e8ca440027240d7655eafc1336add"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-x86_64-alpine.img.tar.xz"
released_at = "2026-08-11T02:47:51Z"

[[images]]
name = "rootfs-x86_64-busybox.img"
version = "0.0.11"
description = "BusyBox rootfs image for x86_64"
sha256 = "bf7a086af3f323660644ade1de07266f234a889fd07cdf369b2a924a522be850"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-x86_64-busybox.img.tar.xz"
released_at = "2026-08-11T02:47:59Z"

[[images]]
name = "rootfs-x86_64-debian.img"
version = "0.0.11"
description = "Debian rootfs image for x86_64"
sha256 = "9872704b624e159b494045fecab358c9d4a08e14933b6e3c6217fa14bf09dba5"
arch = "x86_64"
url = "https://github.com/rcore-os/tgosimages/releases/download/v0.0.11/rootfs-x86_64-debian.img.tar.xz"
released_at = "2026-08-11T02:50:15Z"

