#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../.." && pwd -P)
BUILD_DIR="$(cd "${ROOT_DIR}" && mkdir -p "build" && cd "build" && pwd -P)"

source "${SCRIPT_DIR}/../lib/utils.sh"

# Repository URLs

# Source directories
LINUX_REPO_URL="https://github.com/torvalds/linux.git"
LINUX_SRC_DIR="${BUILD_DIR}/qemu_linux"
LINUX_PATCH_DIR="${ROOT_DIR}/patches/qemu"
ROOTFS_IMAGES_DIR="${ROOT_DIR}/IMAGES/rootfs"
ROOTFS_BUILDERS=()
BUILD_ARGS=()
ROOTFS_STAGE_DIR=""

# Display help information
usage() {
    local usage_arch="${QEMU_ARCH:-}"

    printf 'Build supported OS for QEMU with rootfs support\n'
    printf '\n'
    printf 'Usage:\n'
    if [[ -n "${usage_arch}" ]]; then
        if [[ "${usage_arch}" == "all" ]]; then
            printf '  ./build.sh platform qemu [os] [options]\n'
        else
            printf '  ./build.sh platform qemu-%s [os] [options]\n' "${usage_arch}"
        fi
    else
        printf '  scripts/qemu.sh <command> <os> [options]\n'
        printf '\n'
        printf 'Commands:\n'
        printf '  aarch64                           Build all OS targets for AArch64 architecture\n'
        printf '  x86_64                            Build all OS targets for x86_64 architecture\n'
        printf '  riscv64                           Build all OS targets for RISC-V architecture\n'
        printf '  all                               Build all supported architectures and OS targets\n'
        printf '  help, -h, --help                  Display this help information\n'
        printf '  clean                             Clean build output artifacts\n'
    fi
    printf '\n'
    printf 'OS Targets:\n'
    printf '  linux                             Build the Linux OS\n'
    printf '  arceos                            Build the ArceOS OS (temporarily disabled for QEMU)\n'
    printf '  nimbos                            Build the NimbOS OS\n'
    printf '  zephyr                            Build the Zephyr guest image (aarch64 only)\n'
    printf '  freertos                          Build the FreeRTOS guest image (aarch64 only)\n'
    printf '  all                               Build all OS targets (default)\n'
    printf '  clean                             Clean build output artifacts\n'
    printf '\n'
    printf 'Options:\n'
    printf '  Optional, all options will be directly passed to the specific OS build script\n'
    printf '  --rootfs <list>                   Override default rootfs builders (busybox,alpine,debian)\n'
    printf '\n'
    printf 'Rootfs Packaging:\n'
    printf '  * Rootfs is generated by default for build commands.\n'
    printf '  * Rootfs is not generated for help or clean commands.\n'
    printf '  * Build outputs from all selected OS targets are staged together into /guest/<os>/ inside one rootfs.\n'
    printf '  * Generated rootfs artifacts are stored directly under IMAGES/rootfs.\n'
    printf '\n'
    printf 'Examples:\n'
    if [[ -n "${usage_arch}" ]]; then
        if [[ "${usage_arch}" == "all" ]]; then
            printf '  ./build.sh platform qemu linux\n'
            printf '  ./build.sh platform qemu all --rootfs busybox,alpine,debian\n'
        else
            printf '  ./build.sh platform qemu-%s linux\n' "${usage_arch}"
            printf '  ./build.sh platform qemu-%s all --rootfs busybox,alpine,debian\n' "${usage_arch}"
        fi
    else
        printf '  scripts/qemu.sh aarch64 linux     # Build ARM64 Linux\n'
        printf '  scripts/qemu.sh x86_64 arceos     # Build x86_64 ArceOS (temporarily disabled for QEMU)\n'
        printf '  scripts/qemu.sh riscv64 nimbos    # Build RISC-V NimbOS\n'
        printf '  scripts/qemu.sh aarch64 all --rootfs busybox,alpine,debian\n'
        printf '  scripts/qemu.sh riscv64 all       # Build all OS targets for RISC-V\n'
    fi
}

qemu_arch_images_dir() {
    local arch="$1"
    printf '%s\n' "${ROOT_DIR}/IMAGES/qemu-${arch}"
}

build_rootfs_one() {
    local rootfs_builder="$1"
    local rootfs_script="${SCRIPT_DIR}/../rootfs/${rootfs_builder}.sh"

    if [ ! -f "${rootfs_script}" ]; then
        die "Root filesystem script does not exist: ${rootfs_script}"
    fi

    mkdir -p "${ROOTFS_IMAGES_DIR}"
    info "Creating root filesystem: ${rootfs_script} -> ${ROOTFS_IMAGES_DIR}"

    case "${rootfs_builder}" in
        busybox|alpine|debian)
            bash "${rootfs_script}" "${ARCH}" "--out_dir" "${ROOTFS_IMAGES_DIR}" --guest "${ROOTFS_STAGE_DIR}"
            ;;
        "")
            return 0
            ;;
        *)
            die "Unsupported rootfs builder: ${rootfs_builder} (supported: busybox, alpine, debian)"
            ;;
    esac

    success "Root filesystem creation completed"
}

ensure_rootfs_stage_dir() {
    if [[ -n "${ROOTFS_STAGE_DIR}" ]]; then
        return 0
    fi

    ROOTFS_STAGE_DIR="$(mktemp -d "${BUILD_DIR}/qemu-rootfs-${ARCH}.XXXXXX")"
}

stage_rootfs_payload() {
    local os_name="$1"
    local source_dir="$2"
    local payload_dir

    [[ -d "${source_dir}" ]] || die "Payload source directory not found: ${source_dir}"

    ensure_rootfs_stage_dir
    payload_dir="${ROOTFS_STAGE_DIR}/${os_name}"
    rm -rf "${payload_dir}"
    mkdir -p "${payload_dir}"

    if command -v rsync >/dev/null 2>&1; then
        rsync -a "${source_dir}/" "${payload_dir}/"
    else
        cp -a "${source_dir}/." "${payload_dir}/"
    fi

    printf 'os=%s\narch=%s\nsource=%s\n' "${os_name}" "${ARCH}" "${source_dir}" > "${payload_dir}/manifest.txt"
}

package_os_into_rootfs() {
    local os_name="$1"
    local source_dir="$2"

    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0

    stage_rootfs_payload "${os_name}" "${source_dir}"
}

finalize_rootfs() {
    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0
    [[ -n "${ROOTFS_STAGE_DIR}" && -d "${ROOTFS_STAGE_DIR}" ]] || {
        warn "No guest payload was staged for rootfs generation"
        return 0
    }

    local rootfs_builder
    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        build_rootfs_one "${rootfs_builder}"
    done
}

clean_rootfs_outputs() {
    local rootfs_builder

    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] || return 0

    for rootfs_builder in "${ROOTFS_BUILDERS[@]}"; do
        case "${rootfs_builder}" in
            busybox)
                rm -f "${ROOTFS_IMAGES_DIR}/initramfs-${ARCH}-busybox.cpio.gz"
                rm -f "${ROOTFS_IMAGES_DIR}/rootfs-${ARCH}-busybox.img"
                ;;
            alpine)
                rm -f "${ROOTFS_IMAGES_DIR}/rootfs-${ARCH}-alpine.img"
                ;;
            debian)
                rm -f "${ROOTFS_IMAGES_DIR}/rootfs-${ARCH}-debian.img"
                ;;
            *)
                die "Unsupported rootfs builder: ${rootfs_builder} (supported: busybox, alpine, debian)"
                ;;
        esac
    done
}

linux() {
    info "Cloning ${ARCH} Linux source repository $LINUX_REPO_URL"
    clone_repository "$LINUX_REPO_URL" "$LINUX_SRC_DIR"

    info "Applying patches..."
    apply_patches "$LINUX_PATCH_DIR" "$LINUX_SRC_DIR"

    info "Starting to build ${ARCH} Linux OS..."
    local commands=("$@")
    case "${ARCH}" in
        aarch64)
            local linux_arch="arm64"
            local cross_compile="${AARCH64_CROSS_COMPILE:-aarch64-linux-gnu-}"
            local defconfig="defconfig"
            local kimg_subpath="arch/arm64/boot/Image"
            ;;
        riscv64)
            local linux_arch="riscv"
            local cross_compile="${RISCV64_CROSS_COMPILE:-riscv64-linux-gnu-}"
            local defconfig="defconfig"
            local kimg_subpath="arch/riscv/boot/Image"
            ;;
        x86_64)
            local linux_arch="x86"
            local cross_compile="${X86_CROSS_COMPILE:-}"
            local defconfig="x86_64_defconfig"
            local kimg_subpath="arch/x86/boot/bzImage"
            ;;
        *)
            die "Unsupported Linux architecture: ${ARCH}"
            ;;
    esac
    
    pushd "${LINUX_SRC_DIR}" >/dev/null

    # info "Cleaning Linux: make distclean"
    # make distclean || true

    if [[ "$@" != *"clean"* ]]; then
        if [[ ${#commands[@]} -eq 0 ]] || [[ "${commands[0]}" == "all" ]]; then
            info "Configuring Linux: make ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${defconfig}"
            make ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${defconfig}"
        fi
        
        info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} ${commands[@]}"
        make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "${commands[@]}"
        
        popd >/dev/null

        # If it's a full build, copy the image and create the root filesystem
        if [[ ${#commands[@]} -eq 0 ]] || [[ "${commands[0]}" == "all" ]]; then
            LINUX_IMAGES_DIR="$(qemu_arch_images_dir "${ARCH}")/linux"
            mkdir -p "${LINUX_IMAGES_DIR}"
            KIMG_PATH="${LINUX_SRC_DIR}/${kimg_subpath}"
            [[ -f "${KIMG_PATH}" ]] || die "Kernel image not found: ${KIMG_PATH}"
            info "Copying image: ${KIMG_PATH} -> ${LINUX_IMAGES_DIR}/linux-qemu"
            cp -f "${KIMG_PATH}" "${LINUX_IMAGES_DIR}/linux-qemu"
            
            package_os_into_rootfs "linux" "${LINUX_IMAGES_DIR}"
        fi
    else
        info "Building Linux: make -j$(nproc) ARCH=${linux_arch} CROSS_COMPILE=${cross_compile} clean"
        make -j"$(nproc)" ARCH="${linux_arch}" CROSS_COMPILE="${cross_compile}" "clean"
        LINUX_IMAGES_DIR="$(qemu_arch_images_dir "${ARCH}")/linux"
        info "Removing ${LINUX_IMAGES_DIR}/*"
        rm -rf "${LINUX_IMAGES_DIR}"/* || true
    fi
}

arceos() {
    # Temporarily disable ArceOS build for qemu. Keep the original logic below
    # commented so it can be restored quickly later.
    # case "${ARCH}" in
    #     aarch64)
    #         local platform="aarch64-dyn"
    #         ;;
    #     riscv64)
    #         local platform="riscv64-qemu-virt"
    #         ;;
    #     x86_64)
    #         local platform="x86-pc"
    #         ;;
    #     *)
    #         die "Unsupported ArceOS architecture: ${ARCH}"
    #         ;;
    # esac
    #
    # ARCEOS_IMAGES_DIR="$(qemu_arch_images_dir "${ARCH}")/arceos"
    # info "Building ArceOS using common arceos.sh script for platform: $platform -> $ARCEOS_IMAGES_DIR"
    #
    # # Call the arceos.sh script with proper parameters
    # bash "${SCRIPT_DIR}/../os/arceos.sh" "$platform" --images-dir "$ARCEOS_IMAGES_DIR" --image-name "arceos-qemu" "$@"
    #
    # if [[ "$@" != *"clean"* ]]; then
    #     package_os_into_rootfs "arceos" "${ARCEOS_IMAGES_DIR}"
    # fi

    warn "ArceOS build is temporarily disabled for qemu, skipping ${ARCH}"
}

nimbos() {
    local qemu_images_dir
    local nimbos_images_dir

    qemu_images_dir="$(qemu_arch_images_dir "${ARCH}")"
    nimbos_images_dir="${qemu_images_dir}/nimbos"

    bash "${SCRIPT_DIR}/../os/nimbos.sh" "$ARCH" --images-dir "${nimbos_images_dir}" --image-name "nimbos-qemu" "$@"

    if [[ "$@" != *"clean"* ]]; then
        package_os_into_rootfs "nimbos" "${nimbos_images_dir}"
    else
        rm -rf "${nimbos_images_dir}" || true
    fi
}

zephyr() {
    local zephyr_images_dir

    zephyr_images_dir="$(qemu_arch_images_dir "${ARCH}")/zephyr"

    if [[ "${ARCH}" != "aarch64" ]]; then
        die "Zephyr guest build is currently only supported for qemu aarch64"
    fi

    bash "${SCRIPT_DIR}/../os/zephyr.sh" qemu-aarch64 --images-dir "${zephyr_images_dir}" --image-name "zephyr-qemu" "$@"

    if [[ "$@" != *"clean"* ]]; then
        package_os_into_rootfs "zephyr" "${zephyr_images_dir}"
    fi
}

freertos() {
    local qemu_images_dir
    local freertos_images_dir

    qemu_images_dir="$(qemu_arch_images_dir "${ARCH}")"
    freertos_images_dir="${qemu_images_dir}/freertos"

    if [[ "${ARCH}" != "aarch64" ]]; then
        die "FreeRTOS guest build is currently only supported for qemu aarch64"
    fi

    if [[ "$@" != *"clean"* ]]; then
        bash "${SCRIPT_DIR}/../os/freertos.sh" qemu-aarch64 --images-dir "${freertos_images_dir}" --image-name "freertos-qemu"
        package_os_into_rootfs "freertos" "${freertos_images_dir}"
    else
        bash "${SCRIPT_DIR}/../os/freertos.sh" qemu-aarch64 clean --images-dir "${freertos_images_dir}" --image-name "freertos-qemu"
        rm -rf "${freertos_images_dir}" || true
    fi
}

parse_common_args() {
    BUILD_ARGS=()
    ROOTFS_BUILDERS=()
    local builder
    local seen
    local -A rootfs_seen=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --rootfs)
                [[ $# -ge 2 ]] || die "--rootfs requires a value"
                IFS=',' read -r -a seen <<< "$2"
                for builder in "${seen[@]}"; do
                    [[ -n "${builder}" ]] || continue
                    case "${builder}" in
                        busybox|alpine|debian)
                            [[ -n "${rootfs_seen[${builder}]:-}" ]] && continue
                            rootfs_seen["${builder}"]=1
                            ROOTFS_BUILDERS+=("${builder}")
                            ;;
                        *)
                            die "Unsupported rootfs builder: ${builder} (supported: busybox, alpine, debian)"
                            ;;
                    esac
                done
                shift 2
                ;;
            *)
                BUILD_ARGS+=("$1")
                shift
                ;;
        esac
    done
}

apply_default_rootfs() {
    [[ ${#ROOTFS_BUILDERS[@]} -gt 0 ]] && return 0

    case "${OS}" in
        clean|help|-h|--help|"")
            return 0
            ;;
    esac

    ROOTFS_BUILDERS=(busybox alpine debian)
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cmd="${1:-}"
    shift 1 || true
    case "${cmd}" in
        ""|help|-h|--help)
            usage
            exit 0
            ;;
        aarch64|riscv64|x86_64)
            ARCH="$cmd"
            if [[ $# -eq 0 || "${1:-}" == "help" || "${1:-}" == "-h" || "${1:-}" == "--help" || "${1:-}" == --* ]]; then
                QEMU_ARCH="${ARCH}" usage
                exit 0
            fi
            OS="$1"
            shift 1 || true
            parse_common_args "$@"
            apply_default_rootfs
            trap '[[ -n "${ROOTFS_STAGE_DIR}" ]] && rm -rf "${ROOTFS_STAGE_DIR}"' EXIT
            case "${OS}" in
                linux)
                    linux "${BUILD_ARGS[@]}"
                    ;;
                arceos)
                    arceos "${BUILD_ARGS[@]}"
                    ;;
                nimbos)
                    nimbos "${BUILD_ARGS[@]}"
                    ;;
                zephyr)
                    zephyr "${BUILD_ARGS[@]}"
                    ;;
                freertos)
                    freertos "${BUILD_ARGS[@]}"
                    ;;
                all)
                    linux "${BUILD_ARGS[@]}"
                    arceos "${BUILD_ARGS[@]}"
                    nimbos "${BUILD_ARGS[@]}"
                    if [[ "${ARCH}" == "aarch64" ]]; then
                        zephyr "${BUILD_ARGS[@]}"
                        freertos "${BUILD_ARGS[@]}"
                    fi
                    ;;
                clean)
                    linux "clean"
                    arceos "clean"
                    nimbos "clean"
                    if [[ "${ARCH}" == "aarch64" ]]; then
                        zephyr "clean"
                        freertos "clean"
                    fi
                    clean_rootfs_outputs
                    ;;
                *)
                    die "Unknown os: ${OS} (supported: linux, arceos, nimbos, zephyr, freertos, all)"
                    ;;
            esac
            if [[ "${OS}" != "clean" ]]; then
                finalize_rootfs
            fi
            trap - EXIT
            [[ -n "${ROOTFS_STAGE_DIR}" ]] && rm -rf "${ROOTFS_STAGE_DIR}"
            ;;
        all)
            if [[ $# -eq 0 || "${1:-}" == "help" || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
                QEMU_ARCH="all" usage
                exit 0
            fi

            if [[ "${1:-}" == --* ]]; then
                OS="all"
            else
                OS="$1"
                shift 1 || true
            fi

            for arch in aarch64 riscv64 x86_64; do
                "$0" "$arch" "${OS}" "$@" || { echo "[ERROR] $arch build failed" >&2; exit 1; }
            done
            ;;
        clean)
            for arch in aarch64 riscv64 x86_64; do
                "$0" "$arch" "clean" || { echo "[ERROR] $arch build failed" >&2; exit 1; }
            done
            ;;
        *)
        die "Unknown command: $cmd" >&2
        ;;
    esac
fi
